#!/bin/bash
#
# tmxauditlogd-secure       
# System startup for the tmxauditlogd-secure service.
#
# Author:       Ethan Vaughn
#
# chkconfig:    - 50 01
#
# description:  Enable start/stop of tmxauditlogd-secure wrapper at system start/stop.
# processname:  tmxauditlogd-secure
#

# source function library
. /etc/rc.d/init.d/functions

lockfile=/var/lock/subsys/tmxauditlogd-secure
DAEMON=/usr/sbin/tmxauditlogd-secure

[ -f ${DAEMON} ] || (echo "${DAEMON} missing! Unable to manage tmxauditlogd-secure service."; exit 1)

RETVAL=1

start() {
	if [ -f $lockfile ]; then 
		echo "The tmxauditlogd-secure syslog service is already running."
		echo "Stale lockfile? [$lockfile]";
		exit 1
	fi
	echo -n $"Starting tmxauditlogd-secure syslog services: "
	${DAEMON}
	RETVAL=$?
	touch "$lockfile" 
	[  $RETVAL -eq 0 ] && success || failure
	echo
}

stop() {
	echo -n $"Disabling tmxauditlogd-secure syslog services: "
	PID=$(pgrep -f 'perl.*tmxauditlogd-secure')
	[ $PID ] && kill $PID
	RETVAL=$?
	rm -f "$lockfile"
	[ $RETVAL -eq 0 ] && success || failure
	echo
}

restart() {
	stop
	start
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart|force-reload)
	restart
	;;
reload)
	;;
condrestart)
	[ -f "$lockfile" ] && restart
	;;
status)
	if [ -f $lockfile ]; then
		echo $"tmxauditlogd-secure is running ..."
		RETVAL=0
	else
		echo $"tmxauditlogd-secure is stopped."
		RETVAL=3
	fi
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
	exit 1
esac

exit $RETVAL

