CREATE TABLE device (
	id SERIAL NOT NULL PRIMARY KEY,

	hostname    VARCHAR(128) NOT NULL UNIQUE,
	serialno    VARCHAR(128),
	comment     VARCHAR(128),
	auth_check  TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
	admin_notes TEXT,
	notes       TEXT,
	template_id BIGINT NOT NULL REFERENCES template(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
		DEFERRABLE,
		
	mtime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
	ctime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()

) WITHOUT OIDS;

ALTER SEQUENCE device_id_seq RESTART WITH 100000;
