#!/bin/sh
#
# A startup script for the Lotus Domino 6 server
#
# chkconfig: 345 95 5
# Description: Domino startup/shutdown using the "screen" method. (see the man page for the screen command.)

USER=notes
LOTUSDIR=/u01/app/lotus
BINDIR=${LOTUSDIR}/bin
DATADIR=${LOTUSDIR}/notesdata

function status {
	declare -i numproc=$(pgrep -u $USER -f "app\/lotus\/notes\/latest" | wc -l)

	if [ $numproc -gt 0 ]; then
		printf "\n%5d Domino Processes for user [${USER}]:\n\n" $numproc

		groups="adminp amgr calconn event http imap mtc replica router sched server smtp update"
		#total=0
		for group in $groups; do
			declare -i numproc=$(pgrep -u $USER -f "app\/lotus\/notes\/latest.*${group}" | wc -l)
			printf "%5d $group\n" $numproc
			#total=$[ $total + $numproc ]
		done
		echo

		#echo "DEBUG: total = $total"
	else
		echo
		echo "Domino Server is not running for user [$USER] ..." 
		echo
	fi
}


function start {
	declare -i numproc=$(pgrep -u $USER -f "app\/lotus\/notes\/latest" | wc -l)
	if [ $numproc -gt 0 ]; then
		echo
		echo "[ STARTUP FAILED ] : Domino server already running for user [$USER]."
		status
		exit 1
	fi

	echo -n "Starting Domino server for user [${USER}] ... "
	su - $USER -c "screen -d -m -S ${USER} ${LOTUSDIR}/domino.${USER}.startup"
	echo "done."
}


function stop {
	echo "Stopping Domino server for user ${USER} ..."
	su - $USER -c "cd ${DATADIR}; ${BINDIR}/server -q"
	pkill -9 -u $USER
}


case $1 in

start)
	start
;;

stop)
	stop
;;

restart)
	stop
	start
;;

status)
	status
;;

*)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
;;

esac

exit 0
