#!/usr/bin/perl

use FindBin qw( $Bin );
use lib "$Bin/..";

use lib::objectcache;

use strict;



#----- Main ------------------------------------------------------------------

my $servlist = lib::objectcache::getServDescList();

# Our output is ASCII :
print "Content-type: text/plain\n\n";

foreach my $serv (@$servlist) {
	print "$serv\n";
}


exit (0);
