#!/bin/sh
#
# Init script for maven
#
# chkconfig: 345 95 5
# Description: start/stop wrapper for the /maven/jetty.sh java webserver start/stop script. 

function status {
	retval=0
	if ps faxu |grep -q "^maven.*java.*maven" ; then
		echo "Maven is running ..."
	else 
		echo "Maven is stopped."
		retval=1
	fi
	return $retval
}


function start {
	status
	result=$?
	if [ $result -eq 0 ]; then
		echo
		echo "[ STARTUP FAILED ] : Maven already running."
		exit 1
	fi

	echo -n "Starting Maven ... "
	cd /maven
	./jetty.sh start
	echo "done."
}


function stop {
	status
	result=$?
	if [ $result -ne 0 ]; then
		echo
		echo "[ FAILED ] : Maven not running."
		exit 1
	fi

	echo -n "Stopping Maven ... "
	su - $USER -c "${BINDIR}/stop.sh"
	echo "done."
}


case $1 in

start)
	start
;;

stop)
	stop
;;

restart)
	stop
	start
;;

status)
	status
;;

*)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
;;

esac

exit 0
