#!/bin/bash
#
# chkconfig: 345 95 5
# Description: The LogServer.jar startup/shutdown using the "screen" method. (see the man page for the screen command.)

# ----- GLOBALS --------------------------------------------------------------
PROG=LogServer
PORT=8189
DIR=/u01/app/cclog
BINDIR=${DIR}/bin
DATADIR=${DIR}/data
declare -i PID=0



#----- FUNCTIONS -------------------------------------------------------------
function status {
	# Sets $PID to process ID if running, 0 if stopped.
	PID=$(/usr/bin/screen -ls | grep $PROG | cut -d "." -f1)
}


function start {
	status
	if [ $PID -gt 0 ]; then
		echo "$PROG is already running. PID=[$PID]"
		exit 1
	fi
	
	echo -n "Starting $PROG on port $PORT ... "
	cd $DATADIR
	/usr/bin/screen -d -m -S "$PROG" /usr/bin/java -jar $BINDIR/$PROG.jar $PORT
	status
	echo "done. PID=[$PID]"
}


function stop {
	status
	if [ $PID -eq 0 ]; then
		echo "$PROG is not running."
		exit 1
	fi
	
	echo -n "Stopping $PROG ... "
	kill $PID
	echo "done."
}



#----- MAIN ------------------------------------------------------------------
case $1 in

start)
	start
;;

stop)
	stop
;;

restart)
	stop
	start
;;

status)
	status
	RUN_MSG="$PROG is running as PID [$PID]."
	STP_MSG="$PROG is stopped."
	[ $PID -gt 0 ] && echo $RUN_MSG || echo $STP_MSG
;;

*)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
;;

esac

exit 0
