CREATE TABLE attribval (
	id SERIAL NOT NULL PRIMARY KEY,
 
	item_id BIGINT NOT NULL REFERENCES item(id)
		ON UPDATE CASCADE
        ON DELETE CASCADE
        DEFERRABLE,  
	
	prop_id BIGINT NOT NULL REFERENCES prop(id)
		ON UPDATE CASCADE
        ON DELETE CASCADE
        DEFERRABLE,  
	
	value  VARCHAR(64) NOT NULL,
	
	mtime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
	ctime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
) WITHOUT OIDS;

GRANT SELECT,INSERT,UPDATE,DELETE ON attribval TO appuser;
GRANT ALL ON attribval_id_seq TO appuser;
