CREATE TABLE iptypelink (
	ipaddr_id  BIGINT NOT NULL REFERENCES ipaddr(id)
		ON UPDATE CASCADE
	    ON DELETE CASCADE
	    DEFERRABLE,
	iptype_id  BIGINT NOT NULL REFERENCES iptype(id)
		ON UPDATE CASCADE
        ON DELETE CASCADE
        DEFERRABLE

) WITHOUT OIDS;
