CREATE TABLE iptype (
	id SERIAL NOT NULL PRIMARY KEY,

	name    VARCHAR(128),  

	mtime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
	ctime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()

) WITHOUT OIDS;

INSERT INTO iptype (name) VALUES('DB');
INSERT INTO iptype (name) VALUES('HEARTBEAT');
INSERT INTO iptype (name) VALUES('LOM');
INSERT INTO iptype (name) VALUES('NAT');
INSERT INTO iptype (name) VALUES('PRIMARY');
INSERT INTO iptype (name) VALUES('SERIAL');
INSERT INTO iptype (name) VALUES('STORAGE');
