CREATE TABLE subnet (
	id SERIAL NOT NULL PRIMARY KEY,

	net     BIGINT NOT NULL,
	mask    BIGINT NOT NULL, 
	comment VARCHAR(128),
	vlan    VARCHAR(10),
	
	mtime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
	ctime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()

) WITHOUT OIDS;
